### ISSUE TITLE
Release on NPM

### ISSUE THREAD

**Issue by robertvansteen** [branneman/TinyAnimate#5]
Any chance this package can be released on NPM?

**Comment by branneman** [comment]
Certainly, I'll start working on this soon :)

You can add [Github URLs](https://docs.npmjs.com/files/package.json#github-urls) to your `package.json` in the meantime:

``` json
{
  "dependencies": {
    "tinyanimate": "branneman/TinyAnimate#v0.3.0"
  }
}
```

**Comment by branneman** [comment]
Done!

https://www.npmjs.com/package/TinyAnimate

**Comment by robertvansteen** [comment]
Nice, thanks! 👍
